# Assignment 1, 8-Puzzle Programming

#### Your homework must be implemented in this Notebook file. 
#### You can add as many cells as you want. However, you are not allowed to touch the code below the line "=============".
#### You need to implement the searching functions and the print result functions. The "print_result() function call after "====" line will print out the results in the format indicated in the Assignment description.
#### For the searching functions, feel free to customize the return data types and parameter lists as long as the function name is as required.

Write your name, netID and email here.

### Name: Pardha Saradhi Chodey
### NetID: nz9626
### Email:pchodey@horizon.csueastbay.edu

In [1]:
a = 10
b = 12
a+b

22

In [49]:
#implementation of function "Iterative_deepening_DFS"
import numpy as np
import time
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class Node_DFS:
    def __init__(self,data,parent,cost_g):
        self.data = data
        self.L1 = None
        self.L2 = None
        self.R1 = None
        self.R2 = None
        self.parent = parent
        self.cost_g = cost_g
    def possibility_L1(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[1] == 0:
            return False
        else:
            temp = self.data[index_of_zero[0],index_of_zero[1]-1]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0],index_of_zero[1]-1] = 0
            return new_data,True
    def possibility_L2(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[0] == 2:
            return False
        else:
            temp = self.data[index_of_zero[0]+1,index_of_zero[1]]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0]+1,index_of_zero[1]] = 0
            return new_data,True    
    def possibility_R1(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[1] == 2:
            return False
        else:
            temp = self.data[index_of_zero[0],index_of_zero[1]+1]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0],index_of_zero[1]+1] = 0
            return new_data,True        
    def possibility_R2(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[0] == 0:
            return False
        else:
            temp = self.data[index_of_zero[0]-1,index_of_zero[1]]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0]-1,index_of_zero[1]] = 0
            return new_data,True   
    def Iterative_deepening_DFS(self):
        iteration_counter = 0
        for depth in range(100):
            queue = [self] 
            frontier = set([]) 
            cutoff = [0]
            g_queue = [0]
            iteration_counter += 1
            while queue:
                current_node = queue.pop(0)    
                current_cutoff =cutoff.pop(0)
                current_g = g_queue.pop(0)
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                if np.array_equal(current_node.data,goal_state):
                    steps = current_node.print_result_DFS()
                    return steps,iteration_counter
                else:              
                    if current_cutoff < depth:     
                        if current_node.possibility_R2():
                            new_data,garbage = current_node.possibility_R2()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.R2 = Node_DFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.insert(0,current_node.R2)
                                cutoff.insert(0,current_cutoff+1)
                                g_queue.insert(0,cost_g)
                        if current_node.possibility_R1():
                            new_data,garbage = current_node.possibility_R1()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.R1 = Node_DFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.insert(0,current_node.R1)
                                cutoff.insert(0,current_cutoff+1)
                                g_queue.insert(0,cost_g)
                        if current_node.possibility_L2():
                            new_data,garbage = current_node.possibility_L2()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.L2 = Node_DFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.insert(0,current_node.L2)
                                cutoff.insert(0,current_cutoff+1)
                                g_queue.insert(0,cost_g)       
                        if current_node.possibility_L1():
                            new_data,garbage = current_node.possibility_L1()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.L1 = Node_DFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.insert(0,current_node.L1)
                                cutoff.insert(0,current_cutoff+1)
                                g_queue.insert(0,cost_g)    
    def print_result_DFS(self):
        data_tracking = [self.data]
        g_tracking = [self.cost_g]
        while self.parent:
            self = self.parent
            data_tracking.append(self.data)
            g_tracking.append(self.cost_g)   
        print ('Solution of the first Scenario(IterativeDFS):')
        while data_tracking:
            print (data_tracking.pop()) 
            if data_tracking:
                print('to')
        return len(g_tracking)
    def deepeningDFS_withoutprint(self):
        iteration_counter = 0
        for depth in range(100):
            queue = [self] 
            frontier = set([]) 
            cutoff = [0]
            g_queue = [0]
            iteration_counter += 1
            while queue:
                current_node = queue.pop(0) 
                current_cutoff =cutoff.pop(0)
                current_g = g_queue.pop(0)
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                if np.array_equal(current_node.data,goal_state):
                    steps = current_node.without_result_DFS()
                    return steps,iteration_counter
                else:              
                    if current_cutoff < depth:  
                        if current_node.possibility_R2():
                            new_data,garbage = current_node.possibility_R2()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.R2 = Node_DFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.insert(0,current_node.R2)
                                cutoff.insert(0,current_cutoff+1)
                                g_queue.insert(0,cost_g)
                        if current_node.possibility_R1():
                            new_data,garbage = current_node.possibility_R1()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.R1 = Node_DFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.insert(0,current_node.R1)
                                cutoff.insert(0,current_cutoff+1)
                                g_queue.insert(0,cost_g)
                        if current_node.possibility_L2():
                            new_data,garbage = current_node.possibility_L2()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.L2 = Node_DFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.insert(0,current_node.L2)
                                cutoff.insert(0,current_cutoff+1)
                                g_queue.insert(0,cost_g)
                        if current_node.possibility_L1():
                            new_data,garbage = current_node.possibility_L1()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.L1 = Node_DFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.insert(0,current_node.L1)
                                cutoff.insert(0,current_cutoff+1)
                                g_queue.insert(0,cost_g)
    def without_result_DFS(self):
        g_tracking = [self.cost_g]
        while self.parent:
            self = self.parent
            g_tracking.append(self.cost_g) 
        return len(g_tracking)

In [50]:
#implementation of function "breadthFirstSearch" 
import numpy as np
import time
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class Node_BFS:
    def __init__(self,data,parent,cost_g):
        self.data = data
        self.L1 = None
        self.L2 = None
        self.R1 = None
        self.R2 = None
        self.parent = parent
        self.cost_g = cost_g
    def possibility_L1(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[1] == 0:
            return False
        else:
            temp = self.data[index_of_zero[0],index_of_zero[1]-1]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0],index_of_zero[1]-1] = 0
            return new_data,True
    def possibility_L2(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[0] == 2:
            return False
        else:
            temp = self.data[index_of_zero[0]+1,index_of_zero[1]]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0]+1,index_of_zero[1]] = 0
            return new_data,True
    def possibility_R1(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[1] == 2:
            return False
        else:
            temp = self.data[index_of_zero[0],index_of_zero[1]+1]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0],index_of_zero[1]+1] = 0
            return new_data,True  
    def possibility_R2(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[0] == 0:
            return False
        else:
            temp = self.data[index_of_zero[0]-1,index_of_zero[1]]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0]-1,index_of_zero[1]] = 0
            return new_data,True
    def breadthFirstSearch(self):
            queue = [self] 
            frontier = set([]) 
            iteration_counter = 0
            g_queue = [0]
            while queue:
                current_node = queue.pop(0) 
                current_g = g_queue.pop(0)
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iteration_counter += 1
                if np.array_equal(current_node.data,goal_state):
                    steps = current_node.print_BFS()
                    return steps,iteration_counter
                else:              
                        if current_node.possibility_R2():
                            new_data,garbage = current_node.possibility_R2()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.R2 = Node_BFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.append(current_node.R2)
                                g_queue.append(cost_g)
                        if current_node.possibility_R1():
                            new_data,garbage = current_node.possibility_R1()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.R1 = Node_BFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.append(current_node.R1)
                                g_queue.append(cost_g)
                        if current_node.possibility_L2():
                            new_data,garbage = current_node.possibility_L2()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.L2 = Node_BFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.append(current_node.L2)
                                g_queue.append(cost_g)     
                        if current_node.possibility_L1():
                            new_data,garbage = current_node.possibility_L1()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.L1 = Node_BFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.append(current_node.L1)
                                g_queue.append(cost_g)                           
    def print_BFS(self):
        data_tracking = [self.data]
        g_tracking = [self.cost_g]
        while self.parent:
            self = self.parent
            data_tracking.append(self.data)
            g_tracking.append(self.cost_g)  
        print ('Solution of the first Scenario(BFS):')
        while data_tracking:
            print (data_tracking.pop())
            if data_tracking:
                print ('to')           
        return len(g_tracking)
    def BFS_withoutprint(self):
            queue = [self] 
            frontier = set([]) 
            iteration_counter = 0
            g_queue = [0]
            while queue:
                current_node = queue.pop(0) 
                current_g = g_queue.pop(0)
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iteration_counter += 1
                if np.array_equal(current_node.data,goal_state):
                    steps = current_node.withoutprint_BFS()
                    return steps,iteration_counter
                else:              
                        if current_node.possibility_R2():
                            new_data,garbage = current_node.possibility_R2()
                    
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.R2 = Node_BFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.append(current_node.R2)
                                g_queue.append(cost_g)
                        if current_node.possibility_R1():
                            new_data,garbage = current_node.possibility_R1()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.R1 = Node_BFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.append(current_node.R1)
                                g_queue.append(cost_g)  
                        if current_node.possibility_L2():
                            new_data,garbage = current_node.possibility_L2()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.L2 = Node_BFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.append(current_node.L2)
                                g_queue.append(cost_g)    
                        if current_node.possibility_L1():
                            new_data,garbage = current_node.possibility_L1()
                            if tuple(new_data.reshape(1,9)[0]) not in frontier:
                                cost_g = current_g+1
                                current_node.L1 = Node_BFS(data=new_data,parent=current_node,cost_g=cost_g)
                                queue.append(current_node.L1)
                                g_queue.append(cost_g)     
    def withoutprint_BFS(self):
        g_tracking = [self.cost_g]
        while self.parent:
            self = self.parent
            g_tracking.append(self.cost_g)  
        return len(g_tracking)

In [51]:
#implementation of function "print_result(result)"
def print_result():
    file = open("Input8PuzzleCases.txt")
    caselist=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        caselist.append([])
        for j in range (len(string)):
            caselist[index].append(int(string[j]))
        index+=1
    time_spend_DFS = []
    steps_track_DFS=[]
    iteration_track_DFS = []
    test = np.array(caselist.pop(0)).reshape((3,3))
    root=Node_DFS(data=test,parent=None,cost_g=0)
    start = time.time()
    steps,iteration_counter = root.Iterative_deepening_DFS()
    time_spend_DFS.append(time.time()-start)
    steps_track_DFS.append(steps)
    iteration_track_DFS.append(iteration_counter)
    for i in range(99):

        test = np.array(caselist.pop(0)).reshape((3,3))
        root=Node_DFS(data=test,parent=None,cost_g=0)

        start = time.time()
        steps,iteration_counter = root.deepeningDFS_withoutprint()
        end=time.time()
        time_spend_DFS.append(end-start)
        steps_track_DFS.append(steps)
        iteration_track_DFS.append(iteration_counter)
        print(end-start,steps,iteration_counter)
    file = open("Input8PuzzleCases.txt")
    caselist=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        caselist.append([])
        for j in range (len(string)):
            caselist[index].append(int(string[j]))
        index+=1
    time_spend_BFS = []
    steps_track_BFS=[]
    iteration_track_BFS = []
    test = np.array(caselist.pop(0)).reshape((3,3))
    root=Node_BFS(data=test,parent=None,cost_g=0)
    start = time.time()
    steps,iteration_counter = root.breadthFirstSearch()
    time_spend_BFS.append(time.time()-start)
    steps_track_BFS.append(steps)
    iteration_track_BFS.append(iteration_counter)
    print(time_spend_BFS,steps_track_BFS,iteration_track_BFS)
    for i in range(99):
        test = np.array(caselist.pop(0)).reshape((3,3))
        root=Node_BFS(data=test,parent=None,cost_g=0)
        start = time.time()
        steps,iteration_counter = root.BFS_withoutprint()
        end=time.time()
        time_spend_BFS.append(end-start)
        steps_track_BFS.append(steps)
        iteration_track_BFS.append(iteration_counter)
        print(end-start,steps,iteration_counter)
    print('\t\t\t\t Average_Steps \t Average_Time \t Average_Iterations')
    print('\t Iterative DFS \t ', sum(steps_track_DFS)/100, ' \t ', sum(time_spend_DFS)/100, ' \t ', sum(iteration_track_DFS)/100)
    print('\t BFS \t\t ', sum(steps_track_BFS)/100, ' \t ', sum(time_spend_BFS)/100, ' \t ', sum(iteration_track_BFS)/100)

## You can insert as many cells as you want above
## You are not Allowed to modify the code below this line.

# ============================================================

In [52]:
#you need to implement print_result function to print out the result according to the required format
print_result()

Solution of the first Scenario(IterativeDFS):
[[8 7 5]
 [4 1 2]
 [3 0 6]]
to
[[8 7 5]
 [4 1 2]
 [0 3 6]]
to
[[8 7 5]
 [0 1 2]
 [4 3 6]]
to
[[8 7 5]
 [1 0 2]
 [4 3 6]]
to
[[8 7 5]
 [1 3 2]
 [4 0 6]]
to
[[8 7 5]
 [1 3 2]
 [0 4 6]]
to
[[8 7 5]
 [0 3 2]
 [1 4 6]]
to
[[8 7 5]
 [3 0 2]
 [1 4 6]]
to
[[8 0 5]
 [3 7 2]
 [1 4 6]]
to
[[0 8 5]
 [3 7 2]
 [1 4 6]]
to
[[3 8 5]
 [0 7 2]
 [1 4 6]]
to
[[3 8 5]
 [1 7 2]
 [0 4 6]]
to
[[3 8 5]
 [1 7 2]
 [4 0 6]]
to
[[3 8 5]
 [1 7 2]
 [4 6 0]]
to
[[3 8 5]
 [1 7 0]
 [4 6 2]]
to
[[3 8 5]
 [1 0 7]
 [4 6 2]]
to
[[3 0 5]
 [1 8 7]
 [4 6 2]]
to
[[0 3 5]
 [1 8 7]
 [4 6 2]]
to
[[1 3 5]
 [0 8 7]
 [4 6 2]]
to
[[1 3 5]
 [4 8 7]
 [0 6 2]]
to
[[1 3 5]
 [4 8 7]
 [6 0 2]]
to
[[1 3 5]
 [4 8 7]
 [6 2 0]]
to
[[1 3 5]
 [4 8 0]
 [6 2 7]]
to
[[1 3 5]
 [4 0 8]
 [6 2 7]]
to
[[1 3 5]
 [4 2 8]
 [6 0 7]]
to
[[1 3 5]
 [4 2 8]
 [0 6 7]]
to
[[1 3 5]
 [0 2 8]
 [4 6 7]]
to
[[0 3 5]
 [1 2 8]
 [4 6 7]]
to
[[3 0 5]
 [1 2 8]
 [4 6 7]]
to
[[3 2 5]
 [1 0 8]
 [4 6 7]]
to
[[3 2 5]
 [0 1 8]
 [4 6 


# The output format should be as follows. You only need to give one sample solution as an example.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Solution of the first Scenario:
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### .
#### .
#### .
#### 0 1 2
#### 3 4 5
#### 6 7 8

                Average_Steps    Average_Time      
 IDS
 
 BFS

