# Assignment 2, 8-Puzzle Programming - A Star

### Your homework must be implemented in this Notebook file. 
### You can add as many cells as you want. However, you are not allowed to touch the code below the line "=============".
### You need to implement the two searching functions and the print result functions.
### For the searching functions, feel free to customize the return data types and parameter lists as long as the function name is as required.
### Name:Pardha Saradhi Chodey
### Net I'd: nz9626
### Email I'd: pchodey@horizon.csueastbay.edu

In [6]:
#implementation of function "A Star Misplaced"
import numpy as np
import time
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class Node_astar_misplaced:
    def __init__(self,data,parent,cost_g,cost_h):
        self.data = data
        self.parent = parent
        self.cost_g = cost_g
        self.cost_h = cost_h
        self.L1 = None
        self.L2 = None
        self.R1 = None
        self.R2 = None
    def possibility_L1(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[1] == 0:
            return False
        else:
            temp = self.data[index_of_zero[0],index_of_zero[1]-1]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0],index_of_zero[1]-1] = 0
            return new_data,True
    def possibility_L2(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[0] == 2:
            return False
        else:
            temp = self.data[index_of_zero[0]+1,index_of_zero[1]]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0]+1,index_of_zero[1]] = 0
            return new_data,True
    def possibility_R1(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[1] == 2:
            return False
        else:
            temp = self.data[index_of_zero[0],index_of_zero[1]+1]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0],index_of_zero[1]+1] = 0
            return new_data,True    
    def possibility_R2(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[0] == 0:
            return False
        else:
            temp = self.data[index_of_zero[0]-1,index_of_zero[1]]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0]-1,index_of_zero[1]] = 0
            return new_data,True
    def aStarMisplacedTiles(self):
        queue = [(self,0)] 
        frontier = set([])
        g_queue = [(0,0)]
        iteration_counter = 0
        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                current_node = queue.pop(0)[0]
                g_queue = sorted(g_queue, key=lambda x:x[1])
                current_g = g_queue.pop(0)[0]
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iteration_counter += 1
                if np.array_equal(current_node.data,goal_state):
                    steps=current_node.print_result_astar_misplaced()
                    return steps,iteration_counter
                else:              
                    if current_node.possibility_R2():
                        new_data,garbage = current_node.possibility_R2()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp_h=np.sum(new_data!=goal_state)
                            total_cost = temp_h + cost_g
                            current_node.R2 = Node_astar_misplaced(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.R2,total_cost))
                            g_queue.append((cost_g,total_cost))
                    if current_node.possibility_R1():
                        new_data,garbage = current_node.possibility_R1()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp_h=np.sum(new_data!=goal_state)
                            total_cost = temp_h + cost_g
                            current_node.R1 = Node_astar_misplaced(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.R1,total_cost))
                            g_queue.append((cost_g,total_cost))                               
                    if current_node.possibility_L2():
                        new_data,garbage = current_node.possibility_L2()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp_h=np.sum(new_data!=goal_state)
                            total_cost = temp_h + cost_g 
                            current_node.L2 = Node_astar_misplaced(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.L2,total_cost))
                            g_queue.append((cost_g,total_cost))        
                    if current_node.possibility_L1():
                        new_data,garbage = current_node.possibility_L1()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp_h=np.sum(new_data!=goal_state)
                            total_cost = temp_h + cost_g
                            current_node.L1 = Node_astar_misplaced(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.L1,total_cost))
                            g_queue.append((cost_g,total_cost))          
    def print_result_astar_misplaced(self):
        data_tracking = [self.data]
        g_tracking = [self.cost_g]
        while self.parent:
            self = self.parent
            data_tracking.append(self.data)
            g_tracking.append(self.cost_g)
        print ('Solution of the first Scenario(astr_misplaced):')
        while data_tracking:
            print (data_tracking.pop())
            print ('to') 
        return len(g_tracking)
    def astar_misplaced_withoutprint(self):
        queue = [(self,0)] 
        frontier = set([])
        g_queue = [(0,0)]
        iteration_counter = 0
        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                current_node = queue.pop(0)[0]
                g_queue = sorted(g_queue, key=lambda x:x[1])
                current_g = g_queue.pop(0)[0]
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iteration_counter += 1
                if np.array_equal(current_node.data,goal_state):
                    steps=current_node.without_result_astar_misplaced()
                    return steps,iteration_counter
                else:              
                    if current_node.possibility_R2():
                        new_data,garbage = current_node.possibility_R2()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp_h=np.sum(new_data!=goal_state)
                            total_cost = temp_h + cost_g
                            current_node.R2 = Node_astar_misplaced(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.R2,total_cost))
                            g_queue.append((cost_g,total_cost))
                    if current_node.possibility_R1():
                        new_data,garbage = current_node.possibility_R1()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp_h=np.sum(new_data!=goal_state)
                            total_cost = temp_h + cost_g
                            current_node.R1 = Node_astar_misplaced(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.R1,total_cost))
                            g_queue.append((cost_g,total_cost))                               
                    if current_node.possibility_L2():
                        new_data,garbage = current_node.possibility_L2()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp_h=np.sum(new_data!=goal_state)
                            total_cost = temp_h + cost_g 
                            current_node.L2 = Node_astar_misplaced(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.L2,total_cost))
                            g_queue.append((cost_g,total_cost))
                    if current_node.possibility_L1():
                        new_data,garbage = current_node.possibility_L1()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp_h=np.sum(new_data!=goal_state)
                            total_cost = temp_h + cost_g
                            current_node.L1 = Node_astar_misplaced(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.L1,total_cost))
                            g_queue.append((cost_g,total_cost))
    def without_result_astar_misplaced(self):
        g_tracking = [self.cost_g]
        while self.parent:
            self = self.parent
            g_tracking.append(self.cost_g)
        return len(g_tracking)

In [7]:
#implementation of function "A Star Manhattan Distance"
import numpy as np
import time
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class Node_astar_manhattan:
    def __init__(self,data,parent,cost_g,cost_h):
        self.data = data
        self.parent = parent
        self.cost_g = cost_g
        self.cost_h = cost_h
        self.L1 = None
        self.L2 = None
        self.R1 = None
        self.R2 = None
    def possibility_L1(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[1] == 0:
            return False
        else:
            temp = self.data[index_of_zero[0],index_of_zero[1]-1]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0],index_of_zero[1]-1] = 0
            return new_data,True
    def possibility_L2(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[0] == 2:
            return False
        else:
            temp = self.data[index_of_zero[0]+1,index_of_zero[1]]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0]+1,index_of_zero[1]] = 0
            return new_data,True
    def possibility_R1(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[1] == 2:
            return False
        else:
            temp = self.data[index_of_zero[0],index_of_zero[1]+1]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0],index_of_zero[1]+1] = 0
            return new_data,True
    def possibility_R2(self):
        index_of_zero=np.where(self.data == 0)
        if index_of_zero[0] == 0:
            return False
        else:
            temp = self.data[index_of_zero[0]-1,index_of_zero[1]]
            new_data = self.data.copy()
            new_data[index_of_zero[0],index_of_zero[1]] = temp
            new_data[index_of_zero[0]-1,index_of_zero[1]] = 0
            return new_data,True
    def aStarManhattanDistance(self):
        queue = [(self,0)] 
        frontier = set([])
        g_queue = [(0,0)]
        iteration_counter = 0
        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                current_node = queue.pop(0)[0]
                g_queue = sorted(g_queue, key=lambda x:x[1])
                current_g = g_queue.pop(0)[0]
                #print(current_node.data)
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iteration_counter += 1
                if np.array_equal(current_node.data,goal_state):
                    steps=current_node.print_result_manhattan()
                    return steps,iteration_counter
                else:              
                    if current_node.possibility_R2():
                        new_data,garbage = current_node.possibility_R2()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp = new_data
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]])) 
                            total_cost = temp_h + cost_g
                            current_node.R2 = Node_astar_manhattan(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.R2,total_cost))
                            g_queue.append((cost_g,total_cost))
                    if current_node.possibility_R1():
                        new_data,garbage = current_node.possibility_R1()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp = new_data
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))      
                            total_cost = temp_h + cost_g
                            current_node.R1 = Node_astar_manhattan(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.R1,total_cost))
                            g_queue.append((cost_g,total_cost))                               
                    if current_node.possibility_L2():
                        new_data,garbage = current_node.possibility_L2()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp = new_data
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                            total_cost = temp_h + cost_g 
                            current_node.L2 = Node_astar_manhattan(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.L2,total_cost))
                            g_queue.append((cost_g,total_cost))
                    if current_node.possibility_L1():
                        new_data,garbage = current_node.possibility_L1()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp = new_data
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                            total_cost = temp_h + cost_g
                            current_node.L1 = Node_astar_manhattan(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.L1,total_cost))
                            g_queue.append((cost_g,total_cost))  
    def print_result_manhattan(self):
        data_tracking = [self.data]
        g_tracking = [self.cost_g]
        while self.parent:
            self = self.parent
            data_tracking.append(self.data)
            g_tracking.append(self.cost_g)
        print ('Solution of the first Scenario(astar_manhattan):')
        while data_tracking:
            print (data_tracking.pop())
            print ('to')      
        return len(g_tracking)
    def astar_manhattan_withoutprint(self):
        queue = [(self,0)] 
        frontier = set([])
        g_queue = [(0,0)]
        iteration_counter = 0
        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                current_node = queue.pop(0)[0]
                g_queue = sorted(g_queue, key=lambda x:x[1])
                current_g = g_queue.pop(0)[0]  
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iteration_counter += 1
                if np.array_equal(current_node.data,goal_state):
                    steps=current_node.without_result_manhattan()
                    return steps,iteration_counter
                else:              
                    if current_node.possibility_R2():
                        new_data,garbage = current_node.possibility_R2()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp = new_data
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))        
                            total_cost = temp_h + cost_g
                            current_node.R2 = Node_astar_manhattan(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.R2,total_cost))
                            g_queue.append((cost_g,total_cost))
                    if current_node.possibility_R1():
                        new_data,garbage = current_node.possibility_R1()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp = new_data
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))       
                            total_cost = temp_h + cost_g
                            current_node.R1 = Node_astar_manhattan(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.R1,total_cost))
                            g_queue.append((cost_g,total_cost))                               
                    if current_node.possibility_L2():
                        new_data,garbage = current_node.possibility_L2()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp = new_data
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                            
                            total_cost = temp_h + cost_g 
                            current_node.L2 = Node_astar_manhattan(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.L2,total_cost))
                            g_queue.append((cost_g,total_cost))
                    if current_node.possibility_L1():
                        new_data,garbage = current_node.possibility_L1()
                        if tuple(new_data.reshape(1,9)[0]) not in frontier:
                            cost_g = current_g+1
                            temp = new_data
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                            total_cost = temp_h + cost_g
                            current_node.L1 = Node_astar_manhattan(data=new_data,parent=current_node,cost_g=cost_g,cost_h=temp_h)
                            queue.append((current_node.L1,total_cost))
                            g_queue.append((cost_g,total_cost))
    def without_result_manhattan(self):
        g_tracking = [self.cost_g]
        while self.parent:
            self = self.parent
            g_tracking.append(self.cost_g)
        return len(g_tracking)

In [8]:
#implementation of function "print_result(result)"
def print_result():
    file = open("Input8PuzzleCases.txt")
    caselist=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        caselist.append([])
        for j in range (len(string)):
            caselist[index].append(int(string[j]))
        index+=1
    time_spend_AMIS = []
    steps_track_AMIS=[]
    iteration_track_AMIS = []
    test = np.array(caselist.pop(0)).reshape((3,3))
    root=Node_astar_misplaced(data=test,parent=None,cost_g=0,cost_h=0)
    start = time.time()
    steps,iteration_counter = root.aStarMisplacedTiles()
    end=time.time()
    time_spend_AMIS.append(end-start)
    steps_track_AMIS.append(steps)
    iteration_track_AMIS.append(iteration_counter)
    print('Steps:',steps,'Time Taken:',end-start,'Iteration Counter:',iteration_counter)
    for i in range(19):
        test = np.array(caselist.pop(0)).reshape((3,3))
        root=Node_astar_misplaced(data=test,parent=None,cost_g=0,cost_h=0)
        start = time.time()
        steps,iteration_counter = root.astar_misplaced_withoutprint()
        end=time.time()
        time_spend_AMIS.append(end-start)
        steps_track_AMIS.append(steps)
        iteration_track_AMIS.append(iteration_counter)
        print('Steps:',steps,'Time Taken:',end-start,'Iteration Counter:',iteration_counter)
    # FOR ASTAR_MANHATTAN
    file = open("Input8PuzzleCases.txt")
    caselist=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        caselist.append([])
        for j in range (len(string)):
            caselist[index].append(int(string[j]))
        index+=1
    time_spend_AMAN = []
    steps_track_AMAN=[]
    iteration_track_AMAN = []
    test = np.array(caselist.pop(0)).reshape((3,3))
    root=Node_astar_manhattan(data=test,parent=None,cost_g=0,cost_h=0)
    start = time.time()
    steps,iteration_counter = root.aStarManhattanDistance()
    end=time.time()
    time_spend_AMAN.append(end-start)
    steps_track_AMAN.append(steps)
    iteration_track_AMAN.append(iteration_counter)
    print('Steps:',steps,'Time Taken:',end-start,'Iteration Counter:',iteration_counter)
    for i in range(99):
        test = np.array(caselist.pop(0)).reshape((3,3))
        root=Node_astar_manhattan(data=test,parent=None,cost_g=0,cost_h=0)
        start = time.time()
        steps,iteration_counter = root.astar_manhattan_withoutprint()
        end=time.time()
        time_spend_AMAN.append(end-start)
        steps_track_AMAN.append(steps)
        iteration_track_AMAN.append(iteration_counter)
        print('Steps:',steps,'Time Taken:',end-start,'Iteration Counter:',iteration_counter)
    print('\t\t\t\t Average_Steps \t Average_Time \t Average_Iterations')
    print('\t A*(Misplaced) \t ', sum(steps_track_AMIS)/20, ' \t ', sum(time_spend_AMIS)/20, ' \t ', sum(iteration_track_AMIS)/20)
    print('\t A*(Manhattan) \t ', sum(steps_track_AMAN)/100, ' \t ', sum(time_spend_AMAN)/100, ' \t ', sum(iteration_track_AMAN)/100)

You can insert as many cells as you want above
You are not Allowed to modify the code below this line.
## ===============================

In [9]:
#you need to implement print_result function to print out the result according to the required format
print_result()

Solution of the first Scenario(astr_misplaced):
[[8 7 5]
 [4 1 2]
 [3 0 6]]
to
[[8 7 5]
 [4 0 2]
 [3 1 6]]
to
[[8 7 5]
 [4 2 0]
 [3 1 6]]
to
[[8 7 0]
 [4 2 5]
 [3 1 6]]
to
[[8 0 7]
 [4 2 5]
 [3 1 6]]
to
[[8 2 7]
 [4 0 5]
 [3 1 6]]
to
[[8 2 7]
 [4 1 5]
 [3 0 6]]
to
[[8 2 7]
 [4 1 5]
 [3 6 0]]
to
[[8 2 7]
 [4 1 0]
 [3 6 5]]
to
[[8 2 0]
 [4 1 7]
 [3 6 5]]
to
[[8 0 2]
 [4 1 7]
 [3 6 5]]
to
[[0 8 2]
 [4 1 7]
 [3 6 5]]
to
[[4 8 2]
 [0 1 7]
 [3 6 5]]
to
[[4 8 2]
 [1 0 7]
 [3 6 5]]
to
[[4 0 2]
 [1 8 7]
 [3 6 5]]
to
[[0 4 2]
 [1 8 7]
 [3 6 5]]
to
[[1 4 2]
 [0 8 7]
 [3 6 5]]
to
[[1 4 2]
 [3 8 7]
 [0 6 5]]
to
[[1 4 2]
 [3 8 7]
 [6 0 5]]
to
[[1 4 2]
 [3 0 7]
 [6 8 5]]
to
[[1 4 2]
 [3 7 0]
 [6 8 5]]
to
[[1 4 2]
 [3 7 5]
 [6 8 0]]
to
[[1 4 2]
 [3 7 5]
 [6 0 8]]
to
[[1 4 2]
 [3 0 5]
 [6 7 8]]
to
[[1 0 2]
 [3 4 5]
 [6 7 8]]
to
[[0 1 2]
 [3 4 5]
 [6 7 8]]
to
Steps: 26 Time Taken: 371.54624915122986 Iteration Counter: 40543
Steps: 24 Time Taken: 53.73733448982239 Iteration Counter: 15758
Steps: 17 Time 

Steps: 26 Time Taken: 3.093766450881958 Iteration Counter: 4427
Steps: 26 Time Taken: 4.240659475326538 Iteration Counter: 5242
Steps: 24 Time Taken: 0.31914520263671875 Iteration Counter: 920
Steps: 24 Time Taken: 0.06878256797790527 Iteration Counter: 224
Steps: 19 Time Taken: 0.15761733055114746 Iteration Counter: 378
Steps: 19 Time Taken: 0.1306469440460205 Iteration Counter: 300
Steps: 22 Time Taken: 0.5026247501373291 Iteration Counter: 1072
Steps: 20 Time Taken: 0.17154312133789062 Iteration Counter: 432
Steps: 22 Time Taken: 0.28420352935791016 Iteration Counter: 693
Steps: 25 Time Taken: 1.2097649574279785 Iteration Counter: 2524
Steps: 28 Time Taken: 9.649231672286987 Iteration Counter: 8757
Steps: 26 Time Taken: 0.5964045524597168 Iteration Counter: 1263
Steps: 26 Time Taken: 1.3374254703521729 Iteration Counter: 2574
Steps: 29 Time Taken: 13.538731575012207 Iteration Counter: 10010
Steps: 26 Time Taken: 0.34507203102111816 Iteration Counter: 860
Steps: 26 Time Taken: 4.1887


# The output format should be as follows. You only need to give one sample solution as an example.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Solution of the first Scenario:
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### X X X
#### X X X
#### X X X
#### to
#### .
#### .
#### .
#### 0 1 2
#### 3 4 5
#### 6 7 8

                    Average_Steps    Average_Time      
 Miss Placed
 
 Manhattan Distance

